#cloud-config
users:
  - name: deployer
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ${ssh_public_key}

runcmd:
  - apt update && apt install -y iptables iptables-persistent
  - iptables -F
  - iptables -P INPUT DROP
  - iptables -P FORWARD DROP
  - iptables -P OUTPUT ACCEPT
  - iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
  # first ip is your personal ip if needed, the others are gitlab
  # runners ip
  - iptables -A INPUT -p tcp -s 185.64.149.28 --dport 22 -j ACCEPT # Miranui IP
  - iptables -A INPUT -p tcp -s 5.49.58.184 --dport 22 -j ACCEPT   # Ip maison
  - iptables -A INPUT -p tcp -s 35.231.145.151 --dport 22 -j ACCEPT
  - iptables -A INPUT -p tcp -s 35.243.134.228 --dport 22 -j ACCEPT
  - iptables-save > /etc/iptables/rules.v4

disable_root: true
ssh_pwauth: false
