apiVersion: v1
kind: Namespace
metadata:
  name: hello-app
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hello-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hello-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lucas1712/cloudclever-kube-rex-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: DB_USERNAME
              value: "${DB_USERNAME}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_HOST
              value: "${DB_HOST}"
            - name: DB_PORT
              value: "${DB_PORT}"
            - name: DB_NAME
              value: "${DB_NAME}"
            - name: DB_TYPE
              value: "${DB_TYPE}"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hello-app
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: hello-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: config-volume
          emptyDir: {}
      containers:
        - name: frontend
          image: lucas1712/cloudclever-kube-rex-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: FRONT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: BACKEND_URL
              value: "http://backend.hello-app.svc.cluster.local:5000"
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/config
