apiVersion: v1
kind: Namespace
metadata:
  name: hello-app
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: hello-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: hello-app
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lucas1712/cloudclever-kube-rex-backend:latest # It is recommended to use a specific image tag instead of 'latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "1000m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "1024Mi"
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_NAME
            - name: DB_TYPE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_TYPE
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hello-app
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: hello-app
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      volumes:
        - name: config-volume
          emptyDir: {}
      containers:
        - name: frontend
          image: lucas1712/cloudclever-kube-rex-frontend:latest # It is recommended to use a specific image tag instead of 'latest'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: FRONT_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: BACKEND_URL
              value: "http://backend.hello-app.svc.cluster.local:5000"
          volumeMounts:
            - name: config-volume
              mountPath: /tmp/config
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-backend
  namespace: hello-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend
            port:
              number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app-frontend
  namespace: hello-app
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
