name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  OVH_ENDPOINT: ${{ secrets.OVH_ENDPOINT }}
  OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
  OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
  OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init apply
        run: |
          terraform init
        working-directory: deploy/terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: deploy/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: deploy/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: deploy/terraform

  terraform-apply:
    runs-on: ubuntu-latest
    environment: terraform_holder
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init apply
        run: |
          terraform init
        working-directory: deploy/terraform

      - run: terraform apply -auto-approve
        working-directory: deploy/terraform

  kube-deploy:
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: deploy/terraform

      - name: Extract kubeconfig output
        run: |
          mkdir -p ~/.kube
          terraform output -raw kubeconfig_file_eu_west_par > ~/.kube/config
        working-directory: deploy/terraform

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup env variables
        run: |
          echo "DB_USERNAME=lucas" >> $GITHUB_ENV
          echo "DB_PASSWORD=$(terraform output -raw user_password)" >> $GITHUB_ENV
          echo "DB_HOST=$(terraform output -raw domain)" >> $GITHUB_ENV
          echo "DB_PORT=$(terraform output -raw port)" >> $GITHUB_ENV
          echo "DB_NAME=defaultdb" >> $GITHUB_ENV
          echo "DB_TYPE=mysql+pymysql" >> $GITHUB_ENV
        working-directory: deploy/terraform

      - name: Deploy to Kubernetes
        shell: bash
        run: |
          envsubst < hello.yaml | kubectl apply -f -
          kubectl rollout restart -n hello-app deployment backend-deployment frontend-deployment
        working-directory: deploy/kubernetes
